// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/sign-in": {
    params: {};
  };
  "/auth/sign-up": {
    params: {};
  };
  "/:orgSlug": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/dashboard": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/objectives": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/initiatives": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/tasks": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/knowledge": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/settings": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/settings/members": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/settings/teams": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/settings/departments": {
    params: {
      "orgSlug": string;
    };
  };
  "/:orgSlug/settings/labels": {
    params: {
      "orgSlug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/sign-in" | "/auth/sign-up" | "/:orgSlug" | "/:orgSlug/dashboard" | "/:orgSlug/objectives" | "/:orgSlug/initiatives" | "/:orgSlug/tasks" | "/:orgSlug/knowledge" | "/:orgSlug/settings" | "/:orgSlug/settings/members" | "/:orgSlug/settings/teams" | "/:orgSlug/settings/departments" | "/:orgSlug/settings/labels";
  };
  "layouts/auth.tsx": {
    id: "layouts/auth";
    page: "/auth/sign-in" | "/auth/sign-up";
  };
  "routes/auth/sign-in.tsx": {
    id: "routes/auth/sign-in";
    page: "/auth/sign-in";
  };
  "routes/auth/sign-up.tsx": {
    id: "routes/auth/sign-up";
    page: "/auth/sign-up";
  };
  "layouts/authenticated.tsx": {
    id: "layouts/authenticated";
    page: "/" | "/:orgSlug" | "/:orgSlug/dashboard" | "/:orgSlug/objectives" | "/:orgSlug/initiatives" | "/:orgSlug/tasks" | "/:orgSlug/knowledge" | "/:orgSlug/settings" | "/:orgSlug/settings/members" | "/:orgSlug/settings/teams" | "/:orgSlug/settings/departments" | "/:orgSlug/settings/labels";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "layouts/org.tsx": {
    id: "layouts/org";
    page: "/:orgSlug" | "/:orgSlug/dashboard" | "/:orgSlug/objectives" | "/:orgSlug/initiatives" | "/:orgSlug/tasks" | "/:orgSlug/knowledge" | "/:orgSlug/settings" | "/:orgSlug/settings/members" | "/:orgSlug/settings/teams" | "/:orgSlug/settings/departments" | "/:orgSlug/settings/labels";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/:orgSlug/dashboard";
  };
  "routes/objectives.tsx": {
    id: "routes/objectives";
    page: "/:orgSlug/objectives";
  };
  "routes/initiatives.tsx": {
    id: "routes/initiatives";
    page: "/:orgSlug/initiatives";
  };
  "routes/tasks.tsx": {
    id: "routes/tasks";
    page: "/:orgSlug/tasks";
  };
  "routes/knowledge.tsx": {
    id: "routes/knowledge";
    page: "/:orgSlug/knowledge";
  };
  "layouts/settings.tsx": {
    id: "layouts/settings";
    page: "/:orgSlug/settings" | "/:orgSlug/settings/members" | "/:orgSlug/settings/teams" | "/:orgSlug/settings/departments" | "/:orgSlug/settings/labels";
  };
  "routes/settings/members.tsx": {
    id: "routes/settings/members";
    page: "/:orgSlug/settings/members";
  };
  "routes/settings/teams.tsx": {
    id: "routes/settings/teams";
    page: "/:orgSlug/settings/teams";
  };
  "routes/settings/departments.tsx": {
    id: "routes/settings/departments";
    page: "/:orgSlug/settings/departments";
  };
  "routes/settings/labels.tsx": {
    id: "routes/settings/labels";
    page: "/:orgSlug/settings/labels";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/auth": typeof import("./app/layouts/auth.tsx");
  "routes/auth/sign-in": typeof import("./app/routes/auth/sign-in.tsx");
  "routes/auth/sign-up": typeof import("./app/routes/auth/sign-up.tsx");
  "layouts/authenticated": typeof import("./app/layouts/authenticated.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "layouts/org": typeof import("./app/layouts/org.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/objectives": typeof import("./app/routes/objectives.tsx");
  "routes/initiatives": typeof import("./app/routes/initiatives.tsx");
  "routes/tasks": typeof import("./app/routes/tasks.tsx");
  "routes/knowledge": typeof import("./app/routes/knowledge.tsx");
  "layouts/settings": typeof import("./app/layouts/settings.tsx");
  "routes/settings/members": typeof import("./app/routes/settings/members.tsx");
  "routes/settings/teams": typeof import("./app/routes/settings/teams.tsx");
  "routes/settings/departments": typeof import("./app/routes/settings/departments.tsx");
  "routes/settings/labels": typeof import("./app/routes/settings/labels.tsx");
};